#!/bin/bash

CODE=$(perl -nle 'print $1 if /^version: .*\+(.*)$/' pubspec.yaml)
CODE=$(( CODE + 1 ))
VERSION=$(date -u +"%Y.%m%d.%H%M")
gsed -i "s/^version: .*/version: $VERSION+$CODE/" pubspec.yaml

echo "$VERSION+$CODE"
git tag "$VERSION+$CODE"
git push --tags
